# Generated by Django 3.2.8 on 2022-01-08 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='radio',
            name='contents',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
